language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install coverage
script:
  - ls
  - python -m nose -v
notifications:
  email: "jinhwanlazy@gmail.com"
branches:
  only:
    - master
    - dev
    - /^rc-.*$/
